### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by javimarlop** [ramnathv/sochi#2]
Hi Ramnath,

just in case you are interested, I used this repo to build a similar application with radar plots: [ocpuRadarplot](https://github.com/javimarlop/ocpu-radarplot-sochi). I did not manage to get the inline charts (it opens a new tab) and to save the html charts though... Could you possibly help me with that? Thank you very much in deed! Cheers, Javier

**Comment by ramnathv** [comment]
It is not easy to adapt that OpenCPU application, since it is hard-coded to use `nvd3` and you are using `highcharts`. If you can create a simple, short example, I can help you debug things.

**Comment by javimarlop** [comment]
Thank you for any advice! I plot the chart using "rCharts":

``` r
    a<- rCharts:::Highcharts$new() 
    a$chart(type='line',polar=TRUE, width=600,height = 350)
    a$pane(size='90%')
    a$title(text= "Environmental Variables")
    a$xAxis(categories= rownames(dataf),tickmarkPlacement='on',lineWidth=0)
    a$yAxis(gridLineInterpolation='polygon',lineWidth=0,min=0)
    a$data(dataf,pointPlacement='off')   
    return(a) 
```

In any case, thank you for all your contributions! Cheers, Javier

**Comment by javimarlop** [comment]
...sorry, I forgot to mention that I then use also your "inlinechart" to plot it, but since nothing comes up, I just return the chart, which opens in a new window.

**Comment by javimarlop** [comment]
Dear Ramnath,

problem solved! I just needed to load the right js libraries in the main `index.html` headers and modify a bit the `inlineCharts` function to extract the html code from the object. Thank you for sharing your code!
